<?php

/*********************************************************************
* Extension configuration file for ext "vidi".
*
* Generated by ext 16-12-2014 10:50 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Versatile and Interactive Display - List Component',
  'description' => 'Generic listing of records with versatile ways of interacting with the data, e.g. advanced filter, inline editing, mass editing, ... Veni, vidi, vici!',
  'category' => 'module',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'module' => '',
  'state' => 'beta',
  'uploadfolder' => '0',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'version' => '0.9.1',
  'constraints' =>
  array (
    'depends' =>
    array (
      'cms' => '',
      'fluid' => '',
      'typo3' => '6.2.0-6.2.99',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  )
);
