<?php

/*********************************************************************
* Extension configuration file for ext "vidi".
*
* Generated by ext 09-04-2014 14:53 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Versatile and Interactive Display',
  'description' => 'Display advanced list of records in the BE. Veni, vidi, vici!',
  'category' => 'module',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '0.4.0-dev',
  'constraints' => 
  array (
    'depends' => 
    array (
      'cms' => '',
      'fluid' => '',
      'typo3' => '6.1.0-6.1.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
      'metadata' => '',
    ),
  ),
  'user' => 'fab1en',
  'comment' => 'Change log http://forge.typo3.org/projects/extension-vidi/versions/2628',
);

?>