<?php

/*********************************************************************
* Extension configuration file for ext "vidi".
*
* Generated by ext 15-09-2014 09:43 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Versatile and Interactive Display',
  'description' => 'Generic listing of records with versatile ways of interacting with the data, e.g. advanced filter, inline editing, mass editing, ... Veni, vidi, vici!',
  'category' => 'module',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '0.5.0-dev',
  'constraints' => 
  array (
    'depends' => 
    array (
      'cms' => '',
      'fluid' => '',
      'typo3' => '6.2.0-6.2.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  'user' => 'fab1en',
  'comment' => 'TYPO3 CMS 6.2 compatibility. Change log https://forge.typo3.org/versions/2723',
);

?>